#   H-Roulette V-1.0
#   Plugin made by Herllox (FR)
#   Discord: Herllox#1716

settings:
  #Edit all the inventory text here.
  inventory:
    menu: "&5Roulette &7>>"
    money-add: "&aAdding money"
    money-add-lore:
      - "&fInformations:"
      - "  &f• &7Left click(&a+&e100&7)"
      - "  &f• &7Right click(&a+&e1000&7)"
      - "  &f• &7Shift left click(&a+&e10000&7)"
    money-remove: "&cWithdraw money"
    money-remove-lore:
      - "&fInformations:"
      - "  &f• &7Left click(&c-&e100&7)"
      - "  &f• &7Right click(&c-&e1000&7)"
      - "  &f• &7Shift left click(&c-&e10000&7)"
    select: "&bSelector"
    select-lore:
      - "&fMoney in game: &e%bet%"
      - "&fChoose a color:"
      - " &f%select-icon% %black% &7(&ex&a1.5&7)"
      - " &f%not-select-icon% %red% &7(&ex&a1.5&7)"
      - " &f%not-select-icon% %green% &7(&ex&a5&7)"
      - ""
      - "&7Left click to start."
      - "&7Right click to choose a color."
    red: "&cRed"
    black: "&8Black"
    green: "&aGreen"
    select-icon: "→"
    not-select-icon: "•"

  #Edit the amount the win bet was multiplied
  #ex: you bet 100$ on the red and you won so 100$ become 150$
  multiplier:
    green: 5
    red: 1.5
    black: 1.5
  #Set the maximum amount a player can bet.
  max-bet: 1000000
  #Set the minimum amount a player can bet.
  min-bet: 100

#You can edit all the message of the plugin here.
messages:
  prefix: "&6Roulette &7>>"
  permission: "&cYou don't have permission to do that."
  max-bet: "%prefix% &cYou can't bet more than &e%max-bet%."
  min-bet: "%prefix% &cYou can't bet less than &e%min-bet%."
  need-money: "%prefix% &cYou don't have enought money."
  win-message: "%prefix% &aWell done betting &e%bet% &aand win &e%money%&a."